'use client';
import { FormEvent, useState } from 'react';

function useSubmit(endpoint: string) {
  const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false);
  return { status, busy, async submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setStatus(''); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form)); try { const response = await fetch(endpoint, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setStatus('Sent successfully.'); form.reset(); } catch (error) { setStatus(error instanceof Error ? error.message : 'Unable to send.'); } finally { setBusy(false); } } };
}
const field = 'w-full rounded-xl border border-black/20 bg-white px-4 py-3 text-black';
export function ContactForm() { const state = useSubmit('/api/contact'); return <form onSubmit={state.submit} className="mt-8 grid gap-4"><input className="hidden" name="company" tabIndex={-1} autoComplete="off" /><input className={field} name="name" placeholder="Name" required /><input className={field} type="email" name="email" placeholder="Email" required /><textarea className={field} name="message" rows={7} minLength={10} placeholder="How can we help?" required /><button disabled={state.busy} className="rounded-xl bg-black px-6 py-4 font-semibold text-white">{state.busy ? 'Sending…' : 'Send message'}</button><p role="status">{state.status}</p></form>; }
export function SubmissionForm() { const state = useSubmit('/api/submissions'); return <form onSubmit={state.submit} className="mt-8 grid gap-4"><input className="hidden" name="company" tabIndex={-1} autoComplete="off" /><input className={field} type="url" name="siteUrl" placeholder="https://example.com" required /><input className={field} type="email" name="email" placeholder="Your email" required /><textarea className={field} name="notes" rows={6} placeholder="Why should this site be included?" /><button disabled={state.busy} className="rounded-xl bg-black px-6 py-4 font-semibold text-white">{state.busy ? 'Submitting…' : 'Submit site'}</button><p role="status">{state.status}</p></form>; }
