type CategoryContent = { title: string; description: string; intro: string; secondary: string; focusTags: string[] };

const content: Record<string, CategoryContent> = {
  SaaS: { title: 'SaaS Website Design Inspiration', description: 'Browse curated SaaS website examples with clear product storytelling, conversion-focused layouts, and polished interface systems.', intro: 'Strong SaaS websites make an unfamiliar product understandable quickly. This collection highlights landing pages, product narratives, proof structures, and calls to action worth studying.', secondary: 'Use these references to compare hierarchy and interaction patterns, then adapt the principles to your own product and audience.', focusTags: ['Landing pages', 'Product UI', 'Conversion'] },
  AI: { title: 'AI Website Design Inspiration', description: 'Explore AI website examples focused on trust, product clarity, demonstrations, and modern visual systems.', intro: 'AI products often need to explain complex capabilities without overwhelming visitors. These examples show different approaches to demos, credibility, onboarding, and technical storytelling.', secondary: 'The catalogue is a visual reference, not an endorsement of product claims. Verify factual information on each official website.', focusTags: ['AI products', 'Product demos', 'Trust'] },
  'AI Agent': { title: 'AI Agent Website Inspiration', description: 'Curated AI-agent websites showing workflow explanations, automation demos, and product positioning.', intro: 'Agentic products need especially clear explanations of scope, control, and outcomes. Compare how these sites communicate workflows and human oversight.', secondary: 'Look beyond surface styling and evaluate whether each page makes the product’s role and limitations understandable.', focusTags: ['Agents', 'Automation', 'Workflows'] },
  Portfolio: { title: 'Portfolio Website Design Inspiration', description: 'Browse portfolio websites for designers, studios, photographers, developers, and independent creatives.', intro: 'Portfolio sites balance personality with legibility. This collection helps compare project navigation, case-study pacing, typography, and personal positioning.', secondary: 'Study the underlying presentation decisions rather than copying a visual identity that belongs to another creator.', focusTags: ['Case studies', 'Personal brands', 'Creative work'] },
  'Agency/Studio': { title: 'Agency and Studio Website Inspiration', description: 'Explore design agency and creative studio websites with distinctive portfolios, positioning, and interaction patterns.', intro: 'Agency websites must sell taste and capability at the same time. These examples reveal different ways to frame services, proof, and selected work.', secondary: 'Use the official source link to confirm current services and project information.', focusTags: ['Studios', 'Agencies', 'Selected work'] },
  Fintech: { title: 'Fintech Website Design Inspiration', description: 'Fintech website examples focused on clarity, credibility, security cues, and conversion.', intro: 'Financial products need strong trust signals without becoming visually generic. Compare how these pages explain value, compliance, and product mechanics.', secondary: 'Catalogue summaries are design-oriented and are not financial advice or verified product assessments.', focusTags: ['Finance', 'Trust', 'Product clarity'] },
  'E-commerce': { title: 'E-commerce Website Design Inspiration', description: 'Shop and retail website examples with product discovery, merchandising, and conversion patterns.', intro: 'Commerce design depends on product presentation, navigation, and purchasing confidence. This collection spans focused storefronts and broader retail experiences.', secondary: 'Use these references to compare structure and visual merchandising while keeping your own brand system distinct.', focusTags: ['Retail', 'Product pages', 'Merchandising'] },
  Developer: { title: 'Developer Website Design Inspiration', description: 'Developer-tool and documentation websites with clear technical communication and product onboarding.', intro: 'Developer products succeed when documentation, examples, and product value are easy to scan. These references show several approaches to technical hierarchy.', secondary: 'Always verify implementation details and product capabilities on the official source.', focusTags: ['Dev tools', 'Documentation', 'APIs'] },
  'Crypto/Web3': { title: 'Crypto and Web3 Website Inspiration', description: 'Crypto and Web3 website examples covering product storytelling, communities, protocols, and digital assets.', intro: 'Web3 sites often use expressive visual systems alongside difficult product concepts. Compare how the strongest examples establish hierarchy and legitimacy.', secondary: 'Inclusion is for design reference only and does not verify or endorse a project, token, or financial claim.', focusTags: ['Web3', 'Protocols', 'Communities'] },
  Health: { title: 'Health and Wellness Website Inspiration', description: 'Health, medical, fitness, and wellness website examples with accessible, trust-focused design.', intro: 'Health websites need calm communication, careful hierarchy, and credible information design. This collection shows a range of service and product approaches.', secondary: 'The catalogue does not validate health claims; consult official sources and qualified professionals.', focusTags: ['Healthcare', 'Wellness', 'Accessibility'] },
  Education: { title: 'Education Website Design Inspiration', description: 'Education and learning website examples with course discovery, guidance, and clear information architecture.', intro: 'Education websites must help visitors understand paths, outcomes, and next steps. Compare how these references organize complex learning choices.', secondary: 'Treat descriptions as design context and verify factual offerings directly.', focusTags: ['Learning', 'Courses', 'Information design'] },
  'Media/Entertainment': { title: 'Media and Entertainment Website Inspiration', description: 'Film, publishing, magazine, and entertainment websites with editorial storytelling and immersive visual systems.', intro: 'Media sites use pacing, imagery, and typography to build atmosphere while keeping content discoverable. These examples cover multiple editorial models.', secondary: 'Captured pages may differ from current official websites as designs evolve.', focusTags: ['Film', 'Publishing', 'Editorial'] },
  'Architecture/Real Estate': { title: 'Architecture and Real Estate Website Inspiration', description: 'Architecture, interior, property, and real-estate website examples built around place and visual storytelling.', intro: 'These sites rely on photography, spatial rhythm, and project organization. Compare how they balance immersive visuals with practical information.', secondary: 'Project and property details should always be confirmed on official sources.', focusTags: ['Architecture', 'Property', 'Interiors'] },
  'Food & Beverage': { title: 'Food and Beverage Website Inspiration', description: 'Restaurant, coffee, bakery, and beverage websites with expressive branding and product storytelling.', intro: 'Food and beverage design turns sensory qualities into visual systems. These examples show varied approaches to menus, products, locations, and brand voice.', secondary: 'Menus, availability, and business details can change; confirm them with the source.', focusTags: ['Restaurants', 'Coffee', 'Packaging'] },
  'Travel/Hospitality': { title: 'Travel and Hospitality Website Inspiration', description: 'Hotel, travel, and tourism websites combining discovery, atmosphere, and booking journeys.', intro: 'Hospitality sites need to communicate place and reduce booking uncertainty. Compare how these references use imagery, amenities, and navigation.', secondary: 'Availability and property information belong to the official provider.', focusTags: ['Hotels', 'Travel', 'Booking'] },
  Nonprofit: { title: 'Nonprofit Website Design Inspiration', description: 'Nonprofit and charity website examples focused on missions, evidence, participation, and donations.', intro: 'Nonprofit websites need to make a mission credible and action understandable. These examples show different balances of story, proof, and participation.', secondary: 'Inclusion does not independently validate organizational claims.', focusTags: ['Impact', 'Donations', 'Community'] },
  'Fashion/Retail': { title: 'Fashion and Retail Website Inspiration', description: 'Fashion, apparel, beauty, and jewelry websites with strong art direction and commerce systems.', intro: 'Fashion sites combine editorial identity with practical shopping. Compare how the examples handle collections, campaigns, products, and navigation.', secondary: 'Use these as structural references while preserving original creative direction.', focusTags: ['Fashion', 'Apparel', 'Art direction'] },
  'Music/Audio': { title: 'Music and Audio Website Inspiration', description: 'Music, podcast, and audio-product websites using rhythm, personality, and media-rich presentation.', intro: 'Audio brands must create a visual identity for an auditory experience. These examples show varied approaches to artists, platforms, and products.', secondary: 'Media rights and factual details remain with each official source.', focusTags: ['Music', 'Audio', 'Podcasts'] },
  Photography: { title: 'Photography Website Inspiration', description: 'Photography websites with image-led portfolios, editorial sequencing, and restrained interfaces.', intro: 'Photography websites succeed when the interface supports rather than competes with the work. Compare pacing, grids, and project organization.', secondary: 'Images remain the property of their respective creators and are presented as references.', focusTags: ['Photography', 'Portfolios', 'Image grids'] },
  Typography: { title: 'Typography Website Inspiration', description: 'Typography and type-foundry websites centered on expressive type systems and specimens.', intro: 'Type-focused sites demonstrate scale, rhythm, variable behavior, and specimens. These references are useful for studying typography as interface.', secondary: 'Check licensing and usage terms with each type provider.', focusTags: ['Typefaces', 'Foundries', 'Specimens'] },
  Template: { title: 'Website Template Design Inspiration', description: 'Website template examples presented as visual references in the archive.', intro: 'This collection contains template-oriented examples that passed the public catalogue checks.', secondary: 'AllWebsites.Design does not currently operate a template marketplace; purchase and license details belong to each source.', focusTags: ['Templates', 'Layouts', 'Systems'] },
  Other: { title: 'Other Website Design References', description: 'Unclassified website design references awaiting further editorial taxonomy review.', intro: 'These records passed basic integrity checks but do not yet fit a governed category with enough confidence.', secondary: 'This collection is excluded from indexing until its taxonomy is improved.', focusTags: ['Review queue', 'Mixed sectors'] },
};

export function getCategoryContent(category: string): CategoryContent {
  return content[category] || content.Other;
}
