import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { getWebsiteBySlug, getAllSlugs, getRelatedWebsites } from '@/lib/data';
import { getCategoryColor, slugifyCategory } from '@/lib/categories';
import Header from '@/components/Header'; import Footer from '@/components/Footer'; import RelatedExhibits from '@/components/RelatedExhibits'; import NewsletterPostcard from '@/components/NewsletterPostcard'; import CollageSitePage from '@/components/CollageSitePage'; import SingleSiteHero from '@/components/SingleSiteHero';
import { generateBreadcrumbListSchema, generateWebsiteDesignSchema } from '@/lib/schema'; import { SITE_URL } from '@/lib/site';

interface Props { params: Promise<{ slug: string }> }
export async function generateStaticParams() { return (await getAllSlugs()).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const website = await getWebsiteBySlug(slug); if (!website) return { title: 'Website Not Found' }; const category = website.displayCategory || website.category; const title = `${website.name} Website Design Inspiration & Analysis`; const description = `${website.name} website design inspiration in the ${category} collection. Explore its captured page, source summary, palette, and related references.`; return { title, description, alternates: { canonical: `/sites/${slug}` }, openGraph: { title, description, images: [{ url: website.screenshotUrl, alt: `${website.name} ${category} website design screenshot` }], type: 'website', url: `${SITE_URL}/sites/${slug}` }, twitter: { card: 'summary_large_image', title, description, images: [website.screenshotUrl] } }; }
export default async function DetailPage({ params }: Props) { const { slug } = await params; const website = await getWebsiteBySlug(slug); if (!website) notFound(); const related = await getRelatedWebsites(website); const category = website.displayCategory || website.category; const categorySlug = slugifyCategory(category); const accent = getCategoryColor(category); const breadcrumb = generateBreadcrumbListSchema([{ label: 'Home', href: '/' }, { label: 'Categories', href: '/c' }, { label: category, href: `/c/${categorySlug}` }, { label: website.name, href: `/sites/${slug}` }]); const editorialNote = `Included after automated integrity checks confirmed a valid official destination, a unique canonical URL, and a non-placeholder archive record.${website.descriptionSanitized ? ' The imported description matched unsafe generated copy and was replaced with neutral archive language.' : ''}`; return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(generateWebsiteDesignSchema(website)) }} /><Header /><nav aria-label="Breadcrumb" className="bg-black px-5 pb-4 pt-28 text-sm text-white/60"><div className="mx-auto max-w-[1280px]"><Link href="/">Home</Link> / <Link href={`/c/${categorySlug}`}>{category}</Link> / {website.name}</div></nav><SingleSiteHero siteName={website.name} siteDescription={website.description} category={category} accentColor={accent} image={website.screenshotUrl} /><CollageSitePage title={website.name} category={category} description={website.description} siteUrl={website.url} image={website.screenshotUrl} fullImage={website.fullScreenshotUrl} fontName={inferFontName(website.name)} colors={palette(accent)} accentColor={accent} categorySlug={categorySlug} editorialNote={editorialNote} verificationLabel="Automated integrity check" lastReviewedAt={website.lastReviewedAt || '2026-08-11'} tags={website.tags || []} />{related.length > 0 && <RelatedExhibits websites={related} buttonLink={`/c/${categorySlug}`} />}<NewsletterPostcard accentColor={accent} /><Footer /></>; }
function palette(hex: string) { if (!/^#[0-9a-f]{6}$/i.test(hex)) return ['#F5F5F7', '#1D1D1F', '#0071E3', '#111111']; const r = parseInt(hex.slice(1, 3), 16), g = parseInt(hex.slice(3, 5), 16), b = parseInt(hex.slice(5, 7), 16); const color = (values: number[]) => `#${values.map((value) => Math.round(value).toString(16).padStart(2, '0')).join('')}`; return [color([r + (255-r)*.8, g + (255-g)*.8, b + (255-b)*.8]), hex, color([r*.7,g*.7,b*.7]), '#111111']; }
function inferFontName(name: string) { const lower = name.toLowerCase(); if (lower.includes('apple') || lower.includes('airpod')) return 'SF Pro'; if (lower.includes('google')) return 'Google Sans'; if (lower.includes('microsoft')) return 'Segoe UI'; const fonts = ['Inter', 'SF Pro', 'Helvetica Neue', 'Roboto', 'System UI']; return fonts[name.split('').reduce((sum, char) => sum + char.charCodeAt(0), 0) % fonts.length]; }
